### ISSUE TITLE
problems when trying to train.

### ISSUE THREAD

**Issue by Jerchongkong** [yu45020/Waifu2x#7]
first of all I'm a noob in this and it may seem like a silly question.

When I try to train I get this error:

> Traceback (most recent call last):
  File "train.py", line 15, in <module>
    img_dataset = ImageDBData(db_file='dataset/images.db', db_table="train_images_size_128_noise_1_rgb", max_images=24)
  File "/content/Waifu2x/Dataloader.py", line 113, in __init__
    self.total_images = self.get_num_rows(max_images)
  File "/content/Waifu2x/Dataloader.py", line 128, in get_num_rows
    cursor.execute(f"SELECT MAX(ROWID) FROM {self.db_table}")
sqlite3.OperationalError: no such table: train_images_size_128_noise_1_rgb

honestly I do not know what to do, is there a detailed tutorial to be able to do things right?
In case you ask, I have all the dependencies installed.

I hope not to die ignored.

**Comment by yu45020** [comment]
The training script is merely a demo, and I don't have the skills and time to develop all purpose training script. Indeed, this repo was initially used as a practice to learn PyTorch. You may find PyTorch's official tutorial helpful. 

I use sqlite to store all small patches, so you may need to create your own database to feed the model.
